import config

# -->           HARDWARE
NEXT_TRACK_BUTTON = 0
PREV_TRACK_BUTTON = 1
MODE_BUTTON = 2
REWIND_BUTTON = 6
FORWARD_BUTTON = 7
STOP_BUTTON = 8
PLAY_BUTTON = 9
RECORD_BUTTON = 10

MARKER_SET_BUTTON = 3
MARKER_PREV_BUTTON = 4
MARKER_NEXT_BUTTON = 5

FIRST_KNOB = 11
LAST_KNOB = 18

TRACKS_FIRST_BUTTON = 19
TRACKS_LAST_BUTTON = 42

TRACKS_FIRST_FADER = 43
TRACKS_LAST_FADER = 50
# <--

# -->           CONSTANTS
MAX_VOLUME = 0.8
VOLUME_OFFSET = 0.003
SLEEP_TIME = 0.05
FL_TOTAL_NB_TRACKS = 125
TRANSPORT_CHANNEL = config.TransportChan - 1
MIDI_CHANNEL = config.MIDIChannel - 1
TOGGLE_MODE_BUTTONS = [PLAY_BUTTON, RECORD_BUTTON, MODE_BUTTON]
ONE_BAR_IN_TICKS = 384
FOUR_BARS_IN_TICKS = 1536
HW_DIRTY_LEDS_ALTERNATIVE = 260
# <--
